// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace lab05.Data.Migrations
{
    [DbContext(typeof(CityProvinceContext))]
    partial class CityProvinceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lab05.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("City", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Surrey",
                            Population = 300000,
                            Province = "BC"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Vancouver",
                            Population = 675218,
                            Province = "BC"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Victoria",
                            Population = 92141,
                            Province = "BC"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Kelowna",
                            Population = 132084,
                            Province = "BC"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Toronto",
                            Population = 3000000,
                            Province = "ON"
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Hamilton",
                            Population = 500000,
                            Province = "ON"
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Ottawa",
                            Population = 880000,
                            Province = "ON"
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Montreal",
                            Population = 2000000,
                            Province = "QC"
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "Québec City",
                            Population = 520000,
                            Province = "QC"
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "Sherbrooke",
                            Population = 170000,
                            Province = "QC"
                        });
                });

            modelBuilder.Entity("lab05.Models.Province", b =>
                {
                    b.Property<string>("ProvinceCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceCode");

                    b.ToTable("Province", (string)null);

                    b.HasData(
                        new
                        {
                            ProvinceCode = "BC",
                            ProvinceName = "British Columbia"
                        },
                        new
                        {
                            ProvinceCode = "ON",
                            ProvinceName = "Ontario"
                        },
                        new
                        {
                            ProvinceCode = "QC",
                            ProvinceName = "Quebec"
                        });
                });

            modelBuilder.Entity("lab05.Models.City", b =>
                {
                    b.HasOne("lab05.Models.Province", null)
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceCode");
                });

            modelBuilder.Entity("lab05.Models.Province", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
